version: "3.8"

services:
  db:
    image: mysql:8.0.36-debian
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9090
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 9090
    ports:
      - "8080:80"
    depends_on:
      - db
