name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Este fluxo de trabalho contém uma única tarefa chamada "build"
  build:
    # O tipo de runner que a tarefa será executada
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte da tarefa
    steps:       

    - name: Repository checkout
      uses: actions/checkout@v2
      
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 5544
        script: |
          whoami
