name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup SSH
      run: |
          echo "${{ secrets.SSH_USERNAME }}" 
          echo "${{ secrets.SSH_HOST }}"
          echo "${{ secrets.SSH_PASSWORD }}"

          
    - name: Run deploy script on remote server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -p 5544 'echo "Comando echo executado com sucesso!"'
