name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup SSH
      run: |
          echo "USER: ${{ secrets.SSH_USERNAME }}" 
          echo "HOST: ${{ secrets.SSH_HOST }}"
          echo "PASSWORD:  ${{ secrets.SSH_PASSWORD }}"

          
    - name: Run deploy script on remote server
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 5544
        user: ${{ secrets.SSH_USERNAME }}
        pass: ${{ secrets.SSH_PASSWORD }}
        run: |
          'echo "Comando echo executado com sucesso!"'
